pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh '''
        node --version
        mvn clean package
        java HelloWorld
        '''
      }
    }
  }
}
